### ISSUE TITLE
Process for advisories without a fix?

### ISSUE THREAD

**Issue by saethlin** [rustsec/advisory-db#1092]
@Shnatsel wanted to discuss this https://github.com/rustsec/advisory-db/pull/1079#issuecomment-945198609 and I feel like now is a pretty good time because `arrow-rs` has had this issue open about a soundness bug for a month now without a fix or an advisory: https://github.com/apache/arrow-rs/issues/777 and I think I just found one or two more soundness defects.

So what should be done? Notify the crate author(s) and give them some number of days to patch before issuing an advisory? Do we track time from when an issue is opened identifying the problem as a soundness issue, or from when we tell them that this has prompted a RustSec advisory?

**Comment by jorgecarleitao** [comment]
I agree with incentivizing maintainers to fill their own advisories on every publicly known vulnerability. 

I think Tokyo offered us a good example:

* Unsoundness disclosed on the 2021-7-6 11:45 CET: https://github.com/tokio-rs/tokio/issues/3929
* Patch released on the 2021-7-6 20:06 CET: https://github.com/tokio-rs/tokio/pull/3934
* Advisory PRed on the 2021-7-7 23:47 CET: https://github.com/rustsec/advisory-db/pull/951

(All actions were executed by the maintainer)

It is unfortunate that both developers and maintainers act differently if/when the vulnerability is presented in advisory-db because it incentivizes to _not_ being transparent. IMO we should work towards changing this: imo advisories should a "chore" that maintainers perform as part of a disclosure process; it should not have a negative connotation associated to it - bugs are a fact of life, we are just increasing transparency about them given their implications to infosec.

IMO the decision tree goes a bit like this:

1. maintainers do have the bandwidth to patch:
    * they release a patch and document it in an advisory
    * users update
2. maintainers do not have the bandwidth to patch:
    * they document the issue in an advisory
    * users audit their own code, fix uses of unsound APIs, and add exception to `.cargo/audit.toml` (e.g, like [here](https://github.com/influxdata/influxdb_iox/blob/main/.cargo/audit.toml#L23) or [here](https://github.com/jorgecarleitao/arrow2/blob/main/.cargo/audit.toml#L3))
3. maintainers do not have the bandwidth to document the vulnerability:
    * the community steps in and documents it instead

In this direction, I would consider re-wording the first notification to something like:

> This appears to be an instance of use-after-free, which is usually an exploitable security vulnerability.
>
> If a fix and release is feasible within two weeks, I encourage you to release a patch and file a security advisory at https://github.com/RustSec/advisory-db so that users are notified by `cargo audit` that they should update to a newer version.
>
> If a fix and release is not feasible within two weeks, I encourage you to file a security advisory at https://github.com/RustSec/advisory-db describing the vulnerability and how users can avoid it, so that they are notified by `cargo audit`  that they should audit their code and protect themselves from this vulnerability.

And the second to something like

> Heads up: I have included this issue in the RustSec advisory database. I encourage you to take a look and PR more details on how users can avoid being exposed to it on their own applications.
> 
> Once a fix is released to crates.io, I encourage you to update the advisory with the patched version so that users know that they can update the dependency. :+1:

this may better represent the advisory db as a tool to document vulnerabilities (and how users can protect themselves).

**Comment by alamb** [comment]
FWIW I don't think it is a problem to see the Rustsec database as a public shaming mechanism that helps to raise the priority of security issues of rust projects. I think it is serving that purpose for arrow-rs and that it is a good thing. 

However given that perspective, I would not be surprised if most maintainers of projects will not be the ones filing their rustsec entries about their own projects.

**Comment by Qwaz** [comment]
I'm not sure if you were trying to make a joke, but I think it is very problematic if people start to perceive RustSec as a public shaming mechanism especially for open source projects that the maintainers work voluntarily on. Such a view will make everyone (RustSec people, library maintainers, and bug reporters) involved unhappy and unnecessarily hostile to each other. A bug reporting should be a cooperative process, and I believe an advisory database should be viewed as a communication tool to share knowledge about bugs not as a public database of shameful events.

P.S. I didn't realize that you are an arrow-rs maintainer and thought that you are offending them at first :sweat_smile:

**Comment by alamb** [comment]
> I'm not sure if you were trying to make a joke, but I think it is very problematic if people start to perceive RustSec as a public shaming mechanism especially for open source projects that the maintainers voluntarily work on. 

I was not trying to make a joke. 

>  A bug reporting should be a cooperative process, and I believe an advisory database should be viewed as a communication tool to share knowledge about bugs not as a public database of shameful events.

I agree this would be an ideal outcome

**Comment by alamb** [comment]
BTW I wanted to say that https://github.com/rustsec/advisory-db/pull/1131 (where @saethlin proactively updated the rustsec db when the arrow fix was release) was a really nice experience for me. 

I actually had it on my list of things to do to update the db, but having it done by maintainers of rustsec meant that I came away from the while rustsec experience feeling much more like this is intended to be a communications exercise rather than just additional work foisted from an outside party.

So thank you 🎩

**Comment by pinkforest** [comment]
We have now a pretty fair established policy around this now so closing this as completed.

We do need to do more to educate people about that it helps them and we are not against them but that is wider goal.

It is a difficult thing to do to balance the interests whilst keeping things secure - we can't really have any formulaic method of communication or templates as we have to have a personalised way of communication to motivate the maintainer a.k.a the human touch(tm)

If we need to further discuss this we can do in the discussions - thanks all! :)

If any documentation / guidance / policy needs to be fixed we can file a PR as result of the discussion if any.

**Comment by alamb** [comment]
> It is a difficult thing to do to balance the interests between all the stakeholders - we can't really have any formulaic method of communication or templates as we have to have a personalised way of communication to motivate the maintainer a.k.a the human touch(tm)

These are wise words indeed 👍
