### ISSUE TITLE
r2d2-odbc looks abandoned

### ISSUE THREAD

**Issue by bbigras** [rustsec/advisory-db#1097]
https://github.com/Koka/r2d2-odbc

**Comment by tarcieri** [comment]
Please open an upstream issue on the crate asking if it's maintained, and if you don't get a response, we can assess from there

**Comment by bbigras** [comment]
Is that old issue https://github.com/Koka/r2d2-odbc/issues/120 good enough?

A new one could give the maintainer a last chance.

**Comment by tarcieri** [comment]
I guess I didn't see that issue because it has a confusing title and no description. It's possible the maintainer dismissed it for similar reasons.

I'd suggest opening another issue with a clear title like "Is this crate still maintained?" and link to rustsec/advisory-db#1097 issue in the description.

**Comment by bbigras** [comment]
> This crate is abandoned

Repo owner just replied.

**Comment by tarcieri** [comment]
Okay, sounds like we can move forward with an unmaintained crate advisory
