### ISSUE TITLE
Integer overflow in xml-rs crate

### ISSUE THREAD

**Issue by oherrala** [rustsec/advisory-db#1121]
Upstream issues:
 * https://github.com/netvl/xml-rs/issues/210
 * https://github.com/netvl/xml-rs/issues/204

**Comment by tarcieri** [comment]
It'd definitely be good to file an unmaintained crate advisory if the crate has been abandoned.

Otherwise this is a sort of tricky issue in that we don't want to file advisories for every last potential panic, but the one exception to that has been panics in format parsers that operate on untrusted data (potentially sourced via the network) as that becomes a network DoS vector (not sure we have a written policy for that in particular anywhere).

**Comment by tomaka** [comment]
My latest contribution is from April 2015. I don't think I can be considered a maintainer.

**Comment by pinkforest** [comment]
@tomaka maybe there is someone wants to takeover it or smth considering it has a lot of use ? - 

You might be also potentially able to transfer the crate ownership to someone who could maintain it as you're still listed as owner of the crate - that would be most definitely very helpful I think.

**Comment by netvl** [comment]
Hello,

I'm the owner of that crate, and it is indeed unmaintained because I don't have capacity to do it for a very long time. I would very much like to pass ownership of it to someone else.

That being said, my current employer requires any work on any open-source projects to be approved (I'm not even 100% sure it is okay for me to answer here), so even if I find someone, it will take some time for me to get an approval to do the necessary transfer work — for another project, it took about 3 months from start to end.

Still, if there is anyone willing to take ownership and maintenance work, I will be glad to do it.

**Comment by pinkforest** [comment]
Cool - thanks a lot for taking the time to letting us know -

We don't usually flag advisories around where the maintainer is reachable - the advisory would be for anything totally unreachable

Would you nonetheless be okay for us to do unmaintained informational advisory so it can perhaps make someone step up from the community and where you might be able to start the process ?

Cheers

**Comment by netvl** [comment]
Since I'm the only owner of the repository right now, no one else will be able to do anything with the code except me, and I can't as well without an approval. I will start the process of approval for transferring the repo to someone else (I already have got a person interested in it), but it will take time. I don't think I entirely understand your process, so feel free to do whatever you think is appropriate, given what I just said)

**Comment by pinkforest** [comment]
Ok. We'll file as unmaintained in https://github.com/rustsec/advisory-db/pull/1356 

The new maintainer - if any - can send a PR to withdraw the advisory when back to maintained status. 

Thanks a lot!
