### ISSUE TITLE
`chrono` is unmaintained and has a vulnerable dependency

### ISSUE THREAD

**Issue by portno12** [rustsec/advisory-db#1216]
someone asked about this over a month ago with no official reply. there have been some commits but no releases or fixes for reported vulnerabilities in the `time` dependency. there are many issues and prs for the `time` issue in the repo.

is it time for `cargo audit` to list this as unmaintained since its so widely used and not being properly cared for by the owner/maintainers?

https://github.com/chronotope/chrono/issues/650

**Comment by tarcieri** [comment]
`chrono` is a high-profile crate so we should definitely do our due diligence. However I would agree there's a case to be made that it falls under the WIP guidelines for unmaintained crates being drafted in #1192.

I will ask for input from developers on the linked issue in order to attempt to help determine next steps.

**Comment by tarcieri** [comment]
We have confirmation on https://github.com/chronotope/chrono/issues/650 that `chrono` is maintained. Closing this.
