### ISSUE TITLE
`toml` is unmaintained per its original maintainer

### ISSUE THREAD

**Issue by ghost** [rustsec/advisory-db#1221]
largely used crate the maintainer recognizes but can no longer maintain

https://github.com/alexcrichton/toml-rs/issues/460

**Comment by rusty-snake** [comment]
Alternatives according to https://github.com/toml-lang/toml/wiki are [toml_edit](https://github.com/ordian/toml_edit) and [taplo](https://github.com/tamasfe/taplo).

**Comment by thomcc** [comment]
They did mention they were willing to continue maintenance for security issues (emphasis mine):

>  In the meantime I will not be maintaining this crate *other than if a security issue arises*.

So I don't know that this needs concern for the advisory DB.

**Comment by portno12** [comment]
i actually switched to `toml_edit` too with the `easy` and `serde` features. seems to just work for me, but i have basic usage of it.

**Comment by tarcieri** [comment]
Perhaps `toml_edit`, if it were a near drop-in replacement for `toml`, could be given the `toml` crate name and become the successor implementation?

**Comment by pinkforest** [comment]
@ehuss seems to have picked this up (?) and since the security issues fix promise is there we can close this

If the maintainer says we can flag advisory then we can do so - 

Perhaps re-consider merging toml_edit to toml if that is feasible but we can't do much here.

Re-open if this becomes actionable.
