### ISSUE TITLE
CVE redirect

### ISSUE THREAD

**Issue by eslerm** [rustsec/advisory-db#1253]
It is difficult to find CVEs when the URL of an advisory does not include the CVE.

To find CVE-2021-32714 ([RUSTSEC-2021-0079](https://rustsec.org/advisories/RUSTSEC-2021-0079.html)) one can look through the advisory list chronologically or search the git repo.

It would be helpful if `https://rustsec.org/advisories/CVE-2021-32714` redirected to `https://rustsec.org/advisories/RUSTSEC-2021-0079.html` (or vice-versa).

**Comment by tarcieri** [comment]
The entire site is static and hosted on GitHub Pages.

I'm not sure of a way to implement this without using a solution other than GitHub Pages, and migrating to another solution is not soething we'd do just for the purpose of better redirect support.

**Comment by alex** [comment]
```html
    <meta http-equiv="refresh" content="0;URL='{URL}'" />    
```

where there's a will there's a way :-)

**Comment by tarcieri** [comment]
I'm not sure GitHub Pages will serve the appropriate `Content-Type` if the files don't end in `.html`

**Comment by eslerm** [comment]
On GitHub, the actual file needs to end in `.html` but, the href link does not need to. URLs are fine either way.

Adding to what @alex said, [here is an html and markdown redirect for GitHub.](https://stackoverflow.com/a/36846720)

**Comment by pinkforest** [comment]
We don't have any actionable fix / feature here whilst being either not feasible or there is no way to do with github pages - 

Leaving with no way forward with this issue other than to close it-

Please submit a PR if there is a concrete way to do this but since we don't have a nice way to do it - we'll have to close this.

If a search feature needs to be added or URL redirect then issue could be best in rustsec/rustsec repo please - Thanks!

**Comment by amousset** [comment]
A search field has been added to rustsec.org, with the ability to look up CVE IDs.

**Comment by pinkforest** [comment]
it's definitely something that has been irritating me constantly for a long time :)

Thanks @amousset for picking this up and :ship:  it! :purple_heart:
