### ISSUE TITLE
wee_alloc is unmaintained?

### ISSUE THREAD

**Issue by djc** [rustsec/advisory-db#1394]
See https://www.reddit.com/r/rust/comments/x1cle0/dont_use_wee_alloc_in_production_code_targeting/ and https://github.com/rustwasm/wee_alloc/issues/107.

**Comment by pinkforest** [comment]
Hm looks like so. I'll try to do last desperate email to maintainer and ask what we should do with it

@fitzgen seems active in GitHub - we could nudge people to switch something maintained or would you be happy for people to still use the crate ?

If we were to go nudging people what we should recommend as alternative(s) ? e.g. actionable fix

**Comment by pinkforest** [comment]
@djc want to do a PR or I can do later ? Seems we can flag unmaintained on it <https://github.com/rustwasm/wee_alloc/issues/107#issuecomment-1232046894> .. just need some alternative(s) and maybe we can mention lol_alloc as a honorable research project

**Comment by djc** [comment]
I'm not involved enough to do a PR, just a drive-by issue because of the Reddit thread.

**Comment by pinkforest** [comment]
@Craig-Macomber interested on contributing a PR to mark wee_alloc as unmaintained ?

**Comment by pinkforest** [comment]
I'm looking at the biggest consumer of this lib
https://crates.io/crates/parity-util-mem (7 months ago - 1,481,950 downloads, ~3k a day)

The [crate readme](https://crates.io/crates/parity-util-mem) mentions this as a warning:
https://github.com/paritytech/parity-common/issues/364

@dvdplm might have some ideas around this if non-std alternative allocator is needed today ?

**Comment by bkolobara** [comment]
> @MaxGraey @bkolobara how do you feel about non-std allocators under wasm32 targets ?

I only used the standard allocator and it was good enough for all my stuff (wasm on the backend).

**Comment by pepyakin** [comment]
I would say that wee_alloc is pretty much unmaintained, as it seems I and pretty much every other developer moved on. I would've recommended the users move to something else, but I don't have a good replacement in mind (besides dlmalloc which is the default).

> I'm looking at the biggest consumer of this lib
https://crates.io/crates/parity-util-mem (7 months ago - 1,481,950 downloads, ~3k a day)

I think this is incidental. [Substrate](https://github.com/paritytech/substrate) used to compile to w32-u-u, but not anymore since there is [smoldot](https://github.com/paritytech/smoldot): it relies on the default allocator AFAIK.

**Comment by jsoverson** [comment]
I can echo the other comments. There's value in wee_alloc (et al) but only if it's progressing in step with the community, rust, and WebAssembly. If it's not, people should use the standard allocator.
