### ISSUE TITLE
`claim` seems to be unmaintained.

### ISSUE THREAD

**Issue by vidhanio** [rustsec/advisory-db#1479]
`claim` is unmaintained, and the maintained version is called `claims`. The developer of `claim` has not responded to calls to bump the version of `autocfg` it is pinned at, causing many conflicts with other dependencies.

**Comment by pinkforest** [comment]
Normally we require an issue / communique in the repo / otherwise with maintainer explicitly checking the maintanence status re: potentially fixing any security fixes - I however know the maintainer is completely unreachable so we cna shorten the regular 90 day period I think.

Would you like to send a PR for this ?

For this a template can work: 
https://github.com/rustsec/advisory-db/blob/main/crates/ansi_term/RUSTSEC-2021-0139.md

**Comment by sidunder** [comment]
Can this issue not be closed as per PR #1521 ?

**Comment by pinkforest** [comment]
Yes, PR's usually contain Closes or Fixes #x but in case have to close manually. Thanks!
