### ISSUE TITLE
Buffer overflow in crossbeam skiplist might need advisory

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/advisory-db#1504]
https://github.com/crossbeam-rs/crossbeam/pull/940

**Comment by taiki-e** [comment]
It still reads the valid values that we allocated, so I don't think it causes security issues like buffer overflow right away. However, the informational="unsound" advisory may make sense since it definitely violated the get_unchecked's safety contract.

(In any case, I should release the fix soon...)

**Comment by Shnatsel** [comment]
Thanks for the context! In that case I don't think an advisory is necessary. This may still pose some issues wrt aliasing, but there's a separate issue tracking aliasing issues: https://github.com/crossbeam-rs/crossbeam/issues/878

**Comment by Shnatsel** [comment]
Besides that, I'm not thrilled about this being an `Index` implementation instead of a separate `unsafe fn`. While this probably doesn't cause any issues for end users now, this makes the code easy to mess up when making any changes in the future, so I wouldn't be surprised if I find myself filing an advisory about `crossbeam` later.
