### ISSUE TITLE
`daemonize` unmaintained

### ISSUE THREAD

**Issue by oherrala** [rustsec/advisory-db#1543]
There has been issue asking for new release since 2021-09: https://github.com/knsd/daemonize/issues/46 No commits, no communication, etc. from the author since 2021-07.

There's also issue https://github.com/knsd/daemonize/issues/44#issuecomment-887287257 from 2021-07 where author promised new version in two weeks, however that never happened.

Also ping @knsd, is `daemonize` crate still maintained?

**Comment by pinkforest** [comment]
Yes I think this is a clear cut case - thanks :+1: wanna sketch a quick PR per above ^ ?

**Comment by sidunder** [comment]
I'll write up a PR.

**Comment by breard-r** [comment]
A new version of `daemonize` has been released since this advisory, therefore I don't think this crate should still be considered unmaintained anymore. Moreover, the listed alternatives have not seen any updates for respectively 1 and 2 years, so this advisory could misleads people into replacing a maintained crate by an unmaintained one.

Is it possible to take down this advisory? I see procedures to add new ones but not remove them.

**Comment by tarcieri** [comment]
Advisories can be removed by adding `withdrawn` with the date.

See example here: https://github.com/rustsec/advisory-db/blob/main/README.md#advisory-format

**Comment by breard-r** [comment]
@tarcieri Thank you, I'll create a PR in order to add `withdrawn`!
