### ISSUE TITLE
`mac_address` potential unaligned read

### ISSUE THREAD

**Issue by Berrysoft** [rustsec/advisory-db#1690]
This crate seems unmaintained. The latest version is even not in the public repo: https://github.com/repnop/mac_address/issues/34

There is also unaligned read when dealing with winapi.

I have forked this repo and published [`mac_address2`](https://lib.rs/crates/mac_address2). I will continue maintain this fork.

**Comment by repnop** [comment]
Hi, `mac_address` author here. This is the first time I'm hearing about such an issue with the crate, do you have a reproduction for the unaligned read? And as for the linked issue, looks like I simply forgot to push the commit I made up to Github which I can do today.

**Comment by Berrysoft** [comment]
@repnop Hello, glad to know that you are still maintaining that crate! I will open a PR soon to solve that issue.

**Comment by repnop** [comment]
To catch up anyone looking at this issue: from what I can tell, the issue seems to stem from the fact that Rust and C do not agree on the alignment of structures which contain >4 byte aligned members on the 32-bit Windows ABI. I was providing the WinAPI a properly aligned address with which to fill in with a linked list structure, and it would consistently return me pointers to the next element which were underaligned according to Rust (and correctly so), which triggered a panic on newer nightlies. There's a StackOverflow post describing the behavior here: https://stackoverflow.com/questions/55920103/why-is-the-alignment-the-same-on-32-bit-and-64-bit-systems/55930645#55930645

I just released 1.1.5 which contains a fix for the 32-bit targets and confirmed it doesn't exhibit the issue anymore at the cost of using some more stack space. This feels like a more fundamental issue than just with my crate however, though I don't know how many crates are affected by this disagreement, but given that 32-bit Windows is slated to become deprecated and unsupported (but I'm aware the targets still may be rarely used), and x86 allows unaligned reads without faulting, I'm 1) completely unsurprised that its taken this long for **anyone** to notice this issue, and b) don't feel that this requires any kind of advisory to be sent out, though I could potentially be convinced to yank previous versions, but for now I don't even know if that's really worth the trouble it could put people through considering the small amount of projects that would have actually been affected.

If there's any comments or questions feel free to let me know, I'll try to remember to check back on this issue (though mentioning is ideal).

**Comment by 8573** [comment]
> don't feel that this requires any kind of advisory to be sent out, though I could potentially be convinced to yank previous versions

AFAIK, a RustSec advisory is less disruptive than yanking.  Only users who use the previous versions of the crate would be notified about the advisory, and, if they decline to update to the fixed version, they can ignore the advisory easily if they want.

**Comment by 8573** [comment]
I'll note, to be clear, that RustSec advisories are not sent out by email, unlike [Rust Security Response advisories](https://groups.google.com/g/rustlang-security-announcements), although those are duplicated in RustSec.  RustSec advisories are seen when a user uses a RustSec client to ask "are any of my dependencies subject to advisories?"
