### ISSUE TITLE
'tiberius' is not maintained anymore

### ISSUE THREAD

**Issue by bbigras** [RustSec/advisory-db#261]
According to a private email, for the time being he's not working on the project anymore.

The github repo is read-only now.

https://github.com/steffengy/tiberius

**Comment by tarcieri** [comment]
Are there any recommended alternatives?

**Comment by bbigras** [comment]
I don't know any other MSSQL crate.

The [ODBC](https://crates.io/crates/odbc) one maybe.

It seems the sqlx people are interested in supporting mssql eventually. https://github.com/launchbadge/sqlx/issues/116

**Comment by SonicZentropy** [comment]
I'm using the ODBC crate now, and it does technically function insofaras you can run queries against mssql, but it's very limited and can't be used threaded at all.  Rust desperately needs a real solution, so hopefully sqlx gets there eventually.

**Comment by tarcieri** [comment]
I've added an advisory here:

https://github.com/RustSec/advisory-db/pull/262/files

**Comment by tarcieri** [comment]
Assigned `RUSTSEC-2020-0010` in #263

**Comment by bowmanjd** [comment]
Because this issue comes up near the top of search results, and suggests that tiberius is not maintained anymore, it should be pointed out that Prisma does maintain [this fork](https://github.com/prisma/tiberius). The old steffengy archive even links directly to it. Just noting that here for those who stumble upon this issue.
