### ISSUE TITLE
Any plan to add severity to the crates vulnerabilities

### ISSUE THREAD

**Issue by m-clouddefense** [RustSec/advisory-db#544]
This wil help to determine severity of the RUSTSEC vulnerability

**Comment by alex** [comment]
The template for vulnerabilities already supports a `cvss` field with this data.

That said, Severity is nearly always extremely context sensitive. CVSS scores for vulnerabilities in libraries are almost always useless for this reason, in my experience.

**Comment by tarcieri** [comment]
Note that the `cvss` crate supports computing a severity score according to the Qualitative Severity Rating Scale:

https://docs.rs/cvss/1.0.0/cvss/severity/enum.Severity.html

You can configure a `severity_threshold` in `audit.toml`:

https://github.com/RustSec/cargo-audit/blob/master/audit.toml.example#L8

There's no command-line option for it at the moment though, nor do we really otherwise surface that information.
