### ISSUE TITLE
README doesn't explain the new Markdown-based format

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/advisory-db#767]
The README currently provides a template for the TOML fields, but only has one sentence about the Markdown part:

> Advisories are formatted in Markdown with TOML "front matter". Below is the schema of the "front matter" section of an advisory:

We should make the format more clear, since it leads to confusion for reporters - see e.g. #764

**Comment by tarcieri** [comment]
I'm open to suggestions as to how. It's a bit tricky to write documentation for as the format is Markdown itself.

We could cram everything into [EXAMPLE_ADVISORY.md](https://github.com/RustSec/advisory-db/blob/master/EXAMPLE_ADVISORY.md), but I was trying to keep that simplified since otherwise people were copying and pasting all of the explanatory comments over and over and we always had to tell people to remove them. That occurred dozens of times and so far this has only happened once, so I'd prefer not to repeat that.

**Comment by pinkforest** [comment]
People are generally looking CONTRIBUTING.md which says:

> 3. Write a human-readable Markdown description in the same file, after the ``` marker and a newline. Use [this example advisory](https://raw.githubusercontent.com/rustsec/advisory-db/main/EXAMPLE_ADVISORY.md) as a reference.

Maybe we can just reference various great examples that give people something to look up to around "What good looks like"

@amousset do you have any pet examples you would like to showcase perhaps ? :)
