### ISSUE TITLE
Malformed advisory for prost-types?

### ISSUE THREAD

**Issue by roy-work** [RustSec/advisory-db#957]
[The advisory that was just posted for `prost-types`](https://github.com/RustSec/advisory-db/commit/1889bffd6777aa824e4eb71bc1b2ce1264a60a15) appears to be malformed; `cargo audit` aborts with,

```
error: error loading advisory database: parse error: parse error: omit parameters when specifying affected paths: 'Into<SystemTime>' for key `affected.functions` at line 13 column 13
```

which appears to be a reference to this line https://github.com/RustSec/advisory-db/blob/76294321846adbb7a42ef14a6d5d67b0f781da25/crates/prost-types/RUSTSEC-2021-0073.md#L14

… although the line numbers don't quite match up. (But the error message matches the line pretty directly.)

(If it matters, I'm on `cargo-audit v0.12.0`, though I'm also about to try upgrading.)

**Comment by roy-work** [comment]
So, upgraded, & `v0.15.0` doesn't seem affected by this, so this might be an invalid bug report, depending on whether RustSec supports v0.12.0 of `cargo-audit` or not.

**Comment by Shnatsel** [comment]
Thanks for the report! I've applied a hotfix for now: https://github.com/RustSec/advisory-db/pull/958

The specification is not super accurate regardless because it's 
```toml
functions = { "prost_types::Timestamp::Into<SystemTime>" = ["<= 0.7.0"] }
```
and the affected code is actually `From<Timestamp> for SystemTime`, with the `Into` impl being automatically derived from that.

But I'm not very happy with the hotfix because I think having `"prost_types::Timestamp::Into<SystemTime>` explicitly declared made the advisory more readable.

@tarcieri do we support cargo-audit v0.12 still?

**Comment by tarcieri** [comment]
No. Perhaps we should have an official policy about what versions are supported.

We can also file advisories against `cargo-audit` itself to mark them out of date, however that won't help if they can't parse the advisory database in its current form.

**Comment by Shnatsel** [comment]
0.12 came out a year ago, which is not an unreasonable time period to support... but [no distros seem to actually ship versions that old](https://pkgs.org/search/?q=cargo-audit), so we should be fine.

Am I cleared to roll back the hotfix and break 0.12, then?

**Comment by tarcieri** [comment]
Fine by me. Ideally people should use the latest version of `cargo-audit`.
